services:
    homeanalytica.dataregistry.db:
        image: postgres

    homeanalytica.datacollection.db:
        image: mongo

    homeanalytica.datacollection:
        image: ${DOCKER_REGISTRY-}homeanalyticadatacollection
        build:
          context: .
          dockerfile: HomeAnalytica.DataCollection/Dockerfile
        
    homeanalytica.dataregistry:
        image: ${DOCKER_REGISTRY-}homeanalyticadataregistry
        build:
            context: .
            dockerfile: HomeAnalytica.DataRegistry/Dockerfile
            
    homeanalytica.gateway.yarp:
        image: ${DOCKER_REGISTRY-}homeanalyticagatewayyarp
        build:
            context: .
            dockerfile: HomeAnalytica.Gateway.Yarp/Dockerfile

    homeanalytica.web:
        image: ${DOCKER_REGISTRY-}homeanalyticaweb
        build:
            context: .
            dockerfile: HomeAnalytica.Web/Dockerfile
