services:
    sensor-data-db:
        container_name: sensor-data-db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=sensor_data
        restart: always
        ports:
            - "5440:5432"
        volumes:
          - sensor_data:/var/lib/postgresql/data/

    homeanalytica.analytics:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - TARGET_ENVIRONMENT=Docker
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - data_protection_keys:/root/.aspnet/https

    homeanalytica.datacollection:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - TARGET_ENVIRONMENT=Docker
            - ConnectionStrings__DefaultConnection=Server=sensor-data-db;Port=5432;Database=sensor_data;User Id=postgres;Password=postgres;Include Error Detail=true;TrustServerCertificate=True
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - data_protection_keys:/root/.aspnet/https
        depends_on:
            - sensor-data-db

    homeanalytica.gateway.yarp:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - TARGET_ENVIRONMENT=Docker
        ports:
            - "5610:8080"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - data_protection_keys:/root/.aspnet/https
        depends_on:
            - homeanalytica.datacollection

    homeanalytica.web:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - TARGET_ENVIRONMENT=Docker
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/HomeAnalytica.Web.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=8517c5bc-614d-49b7-8990-ff40578db4a5
        ports:
            - "5600:8080"
            - "6600:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - data_protection_keys:/root/.aspnet/https
