services:
    homeanalytica.dataregistry.db:
        container_name: homeanalytica.dataregistry.db
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=data_registry
        restart: always
        ports:
            - "5440:5432"
        volumes:
            - ${APPDATA}/HomeAnalytica/data_registry:/var/lib/postgresql/data/

    homeanalytica.datacollection.db:
        container_name: homeanalytica.datacollection.db
        environment:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: secret
        ports:
            - "27017:27017"
        volumes:
            - ${APPDATA}/HomeAnalytica/data_collection:/data/db

    homeanalytica.datacollection:
        container_name: homeanalytica.datacollection
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - TARGET_ENVIRONMENT=Docker
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/HomeAnalytica/data_protection_keys:/root/.aspnet/https
        depends_on:
            - homeanalytica.datacollection.db

    homeanalytica.dataregistry:
        container_name: homeanalytica.dataregistry
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - TARGET_ENVIRONMENT=Docker
            - ConnectionStrings__DefaultConnection=Server=sensor-data-db;Port=5432;Database=sensor_data;User Id=postgres;Password=postgres;Include Error Detail=true;TrustServerCertificate=True
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/HomeAnalytica/data_protection_keys:/root/.aspnet/https
        depends_on:
            - homeanalytica.dataregistry.db

    homeanalytica.gateway.yarp:
        container_name: homeanalytica.gateway.yarp
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - TARGET_ENVIRONMENT=Docker
        ports:
            - "5610:8080"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/HomeAnalytica/data_protection_keys:/root/.aspnet/https

    homeanalytica.web:
        container_name: homeanalytica.web
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - TARGET_ENVIRONMENT=Docker
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/HomeAnalytica.Web.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=8517c5bc-614d-49b7-8990-ff40578db4a5
        ports:
            - "5600:8080"
            - "6600:8081"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
            - ${APPDATA}/HomeAnalytica/data_protection_keys:/root/.aspnet/https
